version: '3.8'

services:
  naming-server:
    build: ./naming-server
    ports:
      - "8761:8761"
    networks:
      - microservices-network

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - naming-server
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://naming-server:8761/eureka
    networks:
      - microservices-network

  microservico-impostos:
    build: ./micro-imposto
    ports:
      - "8081:8081"
    depends_on:
      - naming-server
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://naming-server:8761/eureka
    networks:
      - microservices-network

  microservico-registro:
    build: ./micro-registro
    ports:
      - "8082:8082"
    depends_on:
      - naming-server
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://naming-server:8761/eureka
    networks:
      - microservices-network

  sist-vendas:
    build: ./sist-vendas-v2-rep-mem-incompleto
    ports:
      - "8083:8083"
    depends_on:
      - naming-server
      - microservico-impostos
      - microservico-registro
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://naming-server:8761/eureka
      - MICROSERVICO_IMPOSTOS_URL=http://microservico-impostos:8081
      - MICROSERVICO_REGISTRO_URL=http://microservico-registro:8082
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge

